openapi: 3.0.2
info:
  version: '2.0'
  title: 'CNS_TAP Tumor and Patient Specific Factors Calculator'
  description: Patient Specific weights for CNS-TAP
  license:
    name: GNU General Public License v3 (GPL-3)
    url: >-
      https://tldrlegal.com/license/gnu-general-public-license-v3-(gpl-3)#fulltext
  contact:
    name: KGrid Team
    email: kgrid-developers@umich.edu
    url: 'http://kgrid.org'
servers:
  - url: /CNSTAPTPC/tumorPatientCalculator/v2.0
    description: Patient Specific weights for CNS-TAP
tags:
- name: KO Endpoints
  description: CNSTAPTPC Endpoints
paths:
  /cnstap:
    post:
      tags:
        - KO Endpoints
      description: Patient Specific weights for CNS-TAP
      operationId: Patient Specific weights for CNS-TAP
      requestBody:
        description: inputs
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/input'
      responses:
        '200':
          description: response
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/output'
        default:
          description: unexpected error
          content:
            application/json:
              schema:
                $ref: 'https://demo.kgrid.org/schemas/basicerror.yaml'
components:
  schemas:
    input:
      required:
        - pathway
        - percent_tumor
        - parsons_score
      properties:
        pathway:
          type: string
          example: ALK
        percent_tumor:
          type: integer
          example: 0
        parsons_score:
          type: integer
          example: 0
        # patient.features:
        #   type: array
          # items:
            # $ref: 'https://demo.kgrid.org/schemas/patientFeature.yaml'
    output:
      required:
        - result
      properties:
        result:
          type: object
