function intrinsicDrugTable(inputs){
  // inputs = genonmic indicators

// pathway allows the requesting system to indicate a specific tumor target biochemical pathway of interest
  var PW = inputs.pathway;

  var IDT = [
  MK_2206 = {
    "drug_name":"MK_2206",
    "pathway":"AKT",
    "tumor_in_vitro":4,
    "tumor_in_vivo":6,
    "phase_one_safety_data":6,
    "cns_data_with_response":0,
    "brain_penetration":0,
    "fda_approval":0,
    "total_points":16,
  },
  Perifosine = {
    "drug_name":"Perifosine",
    "pathway":"AKT",
    "tumor_in_vitro":2,
    "tumor_in_vivo":0,
    "phase_one_safety_data":6,
    "cns_data_with_response":0,
    "brain_penetration":0,
    "fda_approval":0,
    "total_points":8,
  },
  Ceritinib = {
    "drug_name":"Ceritinib",
    "pathway":"ALK",
    "tumor_in_vitro":2,
    "tumor_in_vivo":0,
    "phase_one_safety_data":6,
    "cns_data_with_response":0,
    "brain_penetration":10,
    "fda_approval":10,
    "total_points":28,
  },
  Alectinib = {
    "drug_name":"Perifosine",
    "pathway":"ALK",
    "tumor_in_vitro":2,
    "tumor_in_vivo":6,
    "phase_one_safety_data":3,
    "cns_data_with_response":5,
    "brain_penetration":10,
    "fda_approval":0,
    "total_points":26,
  },
  Entrectinib = {
    "drug_name":"Entrectinib",
    "pathway":"ALK",
    "tumor_in_vitro":4,
    "tumor_in_vivo":0,
    "phase_one_safety_data":3,
    "cns_data_with_response":10,
    "brain_penetration":10,
    "fda_approval":0,
    "total_points":27,
  },
  Dabrafenib = {
    "drug_name":"Dabrafenib",
    "pathway":"BRAF",
    "tumor_in_vitro":4,
    "tumor_in_vivo":6,
    "phase_one_safety_data":6,
    "cns_data_with_response":10,
    "brain_penetration":5,
    "fda_approval":10,
    "total_points":41,
  },
  Vemurafenib = {
    "drug_name":"Vemurafenib",
    "pathway":"BRAF",
    "tumor_in_vitro":2,
    "tumor_in_vivo":0,
    "phase_one_safety_data":0,
    "cns_data_with_response":10,
    "brain_penetration":5,
    "fda_approval":10,
    "total_points":27,
  },
  Abemaciclib = {
    "drug_name":"Abemaciclib",
    "pathway":"CDK",
    "tumor_in_vitro":2,
    "tumor_in_vivo":6,
    "phase_one_safety_data":0,
    "cns_data_with_response":10,
    "brain_penetration":5,
    "fda_approval":10,
    "total_points":33,
  },
  Palbociclib = {
    "drug_name":"Palbociclib",
    "pathway":"CDK",
    "tumor_in_vitro":2,
    "tumor_in_vivo":6,
    "phase_one_safety_data":0,
    "cns_data_with_response":0,
    "brain_penetration":0,
    "fda_approval":10,
    "total_points":18,
  },
  Ribociclib = {
    "drug_name":"Ribociclib",
    "pathway":"CDK",
    "tumor_in_vitro":2,
    "tumor_in_vivo":0,
    "phase_one_safety_data":6,
    "cns_data_with_response":0,
    "brain_penetration":10,
    "fda_approval":10,
    "total_points":28,
  },
  Lenalidomide = {
    "drug_name":"Lenalidomide",
    "pathway":"CNS generic",
    "tumor_in_vitro":2,
    "tumor_in_vivo":0,
    "phase_one_safety_data":6,
    "cns_data_with_response":10,
    "brain_penetration":10,
    "fda_approval":10,
    "total_points":38,
  },
  Olaparib = {
    "drug_name":"Olaparib",
    "pathway":"CNS generic",
    "tumor_in_vitro":4,
    "tumor_in_vivo":6,
    "phase_one_safety_data":0,
    "cns_data_with_response":5,
    "brain_penetration":0,
    "fda_approval":10,
    "total_points":25,
  },
  Gemcitabine = {
    "drug_name":"Gemcitabine",
    "pathway":"CNS generic",
    "tumor_in_vitro":4,
    "tumor_in_vivo":6,
    "phase_one_safety_data":0,
    "cns_data_with_response":5,
    "brain_penetration":10,
    "fda_approval":10,
    "total_points":35,
  },
  Erlotinib = {
    "drug_name":"Erlotinib",
    "pathway":"EGFR",
    "tumor_in_vitro":4,
    "tumor_in_vivo":0,
    "phase_one_safety_data":6,
    "cns_data_with_response":-10,
    "brain_penetration":10,
    "fda_approval":10,
    "total_points":20,
  },
  Osimertinib_Mesylate = {
    "drug_name":"Osimertinib_Mesylate",
    "pathway":"EGFR",
    "tumor_in_vitro":2,
    "tumor_in_vivo":6,
    "phase_one_safety_data":0,
    "cns_data_with_response":5,
    "brain_penetration":10,
    "fda_approval":10,
    "total_points":33,
  },
  Pazopanib_FGFR = {
    "drug_name":"Pazopanib_FGFR",
    "pathway":"FGFR",
    "tumor_in_vitro":4,
    "tumor_in_vivo":6,
    "phase_one_safety_data":6,
    "cns_data_with_response":5,
    "brain_penetration":5,
    "fda_approval":10,
    "total_points":36,
  },
  Ponatinib_FGFR = {
    "drug_name":"Ponatinib_FGFR",
    "pathway":"FGFR",
    "tumor_in_vitro":4,
    "tumor_in_vivo":6,
    "phase_one_safety_data":0,
    "cns_data_with_response":5,
    "brain_penetration":10,
    "fda_approval":10,
    "total_points":35,
  },
  Erdafitinib_FGFR = {
    "drug_name":"Erdafitinib_FGFR",
    "pathway":"FGFR",
    "tumor_in_vitro":4,
    "tumor_in_vivo":6,
    "phase_one_safety_data":0,
    "cns_data_with_response":5,
    "brain_penetration":0,
    "fda_approval":0,
    "total_points":15,
  },
  Debio_1347 = {
    "drug_name":"Debio_1347",
    "pathway":"FGFR",
    "tumor_in_vitro":2,
    "tumor_in_vivo":1,
    "phase_one_safety_data":0,
    "cns_data_with_response":0,
    "brain_penetration":0,
    "fda_approval":0,
    "total_points":3,
  },
  Afatinib = {
    "drug_name":"Afatinib",
    "pathway":"EGFR/HER2/HER4/cMET",
    "tumor_in_vitro":4,
    "tumor_in_vivo":6,
    "phase_one_safety_data":3,
    "cns_data_with_response":-10,
    "brain_penetration":0,
    "fda_approval":10,
    "total_points":13,
  },
  Panobinostat = {
    "drug_name":"Panobinostat",
    "pathway":"HDAC",
    "tumor_in_vitro":2,
    "tumor_in_vivo":6,
    "phase_one_safety_data":6,
    "cns_data_with_response":10,
    "brain_penetration":0,
    "fda_approval":10,
    "total_points":34,
  },
  Vorinostat = {
    "drug_name":"Vorinostat",
    "pathway":"HDAC",
    "tumor_in_vitro":2,
    "tumor_in_vivo":6,
    "phase_one_safety_data":6,
    "cns_data_with_response":-10,
    "brain_penetration":10,
    "fda_approval":10,
    "total_points":24,
  },
  Entinostat = {
    "drug_name":"Entinostat",
    "pathway":"HDAC",
    "tumor_in_vitro":4,
    "tumor_in_vivo":6,
    "phase_one_safety_data":3,
    "cns_data_with_response":0,
    "brain_penetration":5,
    "fda_approval":0,
    "total_points":18,
  },
  Onc201 = {
    "drug_name":"Onc201",
    "pathway":"HDAC",
    "tumor_in_vitro":4,
    "tumor_in_vivo":6,
    "phase_one_safety_data":3,
    "cns_data_with_response":10,
    "brain_penetration":10,
    "fda_approval":0,
    "total_points":33,
  },
  Valproic_Acid = {
    "drug_name":"Valproic_Acid",
    "pathway":"HDAC",
    "tumor_in_vitro":4,
    "tumor_in_vivo":3,
    "phase_one_safety_data":6,
    "cns_data_with_response":0,
    "brain_penetration":10,
    "fda_approval":10,
    "total_points":33,
  },
  Alisertib = {
    "drug_name":"Alisertib",
    "pathway":"INI1",
    "tumor_in_vitro":4,
    "tumor_in_vivo":6,
    "phase_one_safety_data":6,
    "cns_data_with_response":10,
    "brain_penetration":10,
    "fda_approval":0,
    "total_points":36,
  },
  Tamoxifen = {
    "drug_name":"Tamoxifen",
    "pathway":"INI1",
    "tumor_in_vitro":2,
    "tumor_in_vivo":0,
    "phase_one_safety_data":0,
    "cns_data_with_response":0,
    "brain_penetration":10,
    "fda_approval":10,
    "total_points":22,
  },
  Tazemetostat = {
    "drug_name":"Tazemetostat",
    "pathway":"INI1",
    "tumor_in_vitro":2,
    "tumor_in_vivo":0,
    "phase_one_safety_data":3,
    "cns_data_with_response":0,
    "brain_penetration":5,
    "fda_approval":0,
    "total_points":10,
  },
  Trametinib = {
    "drug_name":"Trametinib",
    "pathway":"MEK",
    "tumor_in_vitro":2,
    "tumor_in_vivo":3,
    "phase_one_safety_data":3,
    "cns_data_with_response":5,
    "brain_penetration":10,
    "fda_approval":10,
    "total_points":33,
  },
  Selumetinib = {
    "drug_name":"Selumetinib",
    "pathway":"MEK",
    "tumor_in_vitro":4,
    "tumor_in_vivo":0,
    "phase_one_safety_data":0,
    "cns_data_with_response":0,
    "brain_penetration":10,
    "fda_approval":0,
    "total_points":14,
  },
  Cobimetinib = {
    "drug_name":"Cobimetinib",
    "pathway":"MEK",
    "tumor_in_vitro":4,
    "tumor_in_vivo":0,
    "phase_one_safety_data":0,
    "cns_data_with_response":0,
    "brain_penetration":5,
    "fda_approval":10,
    "total_points":19,
  },
  Binimetinib = {
    "drug_name":"Binimetinib",
    "pathway":"MEK",
    "tumor_in_vitro":4,
    "tumor_in_vivo":0,
    "phase_one_safety_data":0,
    "cns_data_with_response":5,
    "brain_penetration":0,
    "fda_approval":10,
    "total_points":19,
  },
  Crenolanib = {
    "drug_name":"Crenolanib",
    "pathway":"PDGFR",
    "tumor_in_vitro":2,
    "tumor_in_vivo":0,
    "phase_one_safety_data":3,
    "cns_data_with_response":0,
    "brain_penetration":0,
    "fda_approval":0,
    "total_points":5,
  },
  Dasatinib = {
    "drug_name":"Dasatinib",
    "pathway":"PDGFR",
    "tumor_in_vitro":4,
    "tumor_in_vivo":6,
    "phase_one_safety_data":6,
    "cns_data_with_response":5,
    "brain_penetration":10,
    "fda_approval":10,
    "total_points":41,
  },
  Pazopanib_PDGFR = {
    "drug_name":"Pazopanib_PDGFR",
    "pathway":"PDGFR",
    "tumor_in_vitro":4,
    "tumor_in_vivo":6,
    "phase_one_safety_data":6,
    "cns_data_with_response":5,
    "brain_penetration":5,
    "fda_approval":10,
    "total_points":36,
  },
  Ponatinib_PDGFR = {
    "drug_name":"Ponatinib_PDGFR",
    "pathway":"PDGFR",
    "tumor_in_vitro":4,
    "tumor_in_vivo":6,
    "phase_one_safety_data":0,
    "cns_data_with_response":5,
    "brain_penetration":10,
    "fda_approval":10,
    "total_points":35,
  },
  Sorafenib = {
    "drug_name":"Sorafenib",
    "pathway":"PDGFR",
    "tumor_in_vitro":2,
    "tumor_in_vivo":0,
    "phase_one_safety_data":6,
    "cns_data_with_response":0,
    "brain_penetration":0,
    "fda_approval":10,
    "total_points":18,
  },
  Sunitinib = {
    "drug_name":"Sunitinib",
    "pathway":"PDGFR",
    "tumor_in_vitro":2,
    "tumor_in_vivo":6,
    "phase_one_safety_data":6,
    "cns_data_with_response":5,
    "brain_penetration":0,
    "fda_approval":10,
    "total_points":29,
  },
  BKM120 = {
    "drug_name":"BKM120",
    "pathway":"PI3K/mTOR",
    "tumor_in_vitro":4,
    "tumor_in_vivo":6,
    "phase_one_safety_data":0,
    "cns_data_with_response":0,
    "brain_penetration":5,
    "fda_approval":0,
    "total_points":15,
  },
  GDC_0084 = {
    "drug_name":"GDC_0084",
    "pathway":"PI3K/mTOR",
    "tumor_in_vitro":4,
    "tumor_in_vivo":0,
    "phase_one_safety_data":0,
    "cns_data_with_response":10,
    "brain_penetration":10,
    "fda_approval":0,
    "total_points":24,
  },
  Everolimus = {
    "drug_name":"Everolimus",
    "pathway":"PI3K/mTOR",
    "tumor_in_vitro":2,
    "tumor_in_vivo":0,
    "phase_one_safety_data":6,
    "cns_data_with_response":10,
    "brain_penetration":5,
    "fda_approval":10,
    "total_points":33,
  },
  Temsirolimus = {
    "drug_name":"Temsirolimus",
    "pathway":"PI3K/mTOR",
    "tumor_in_vitro":4,
    "tumor_in_vivo":6,
    "phase_one_safety_data":6,
    "cns_data_with_response":-5,
    "brain_penetration":5,
    "fda_approval":10,
    "total_points":26,
  },
  LY3023414 = {
    "drug_name":"LY3023414",
    "pathway":"PI3K/mTOR",
    "tumor_in_vitro":4,
    "tumor_in_vivo":3,
    "phase_one_safety_data":0,
    "cns_data_with_response":5,
    "brain_penetration":5,
    "fda_approval":0,
    "total_points":17,
  },
  Crizotinib = {
    "drug_name":"Crizotinib",
    "pathway":"MET",
    "tumor_in_vitro":4,
    "tumor_in_vivo":6,
    "phase_one_safety_data":6,
    "cns_data_with_response":5,
    "brain_penetration":0,
    "fda_approval":10,
    "total_points":31,
  },
  Cabozantinib = {
    "drug_name":"Cabozantinib",
    "pathway":"MET/VEGF2",
    "tumor_in_vitro":4,
    "tumor_in_vivo":6,
    "phase_one_safety_data":6,
    "cns_data_with_response":10,
    "brain_penetration":10,
    "fda_approval":10,
    "total_points":46,
  },
  Prexasertib = {
    "drug_name":"Prexasertib",
    "pathway":"Chk1",
    "tumor_in_vitro":2,
    "tumor_in_vivo":6,
    "phase_one_safety_data":0,
    "cns_data_with_response":0,
    "brain_penetration":0,
    "fda_approval":0,
    "total_points":8,
  },
  Etoposide = {
    "drug_name":"Etoposide",
    "pathway":"generic cytotoxic",
    "tumor_in_vitro":4,
    "tumor_in_vivo":6,
    "phase_one_safety_data":6,
    "cns_data_with_response":10,
    "brain_penetration":0,
    "fda_approval":10,
    "total_points":36,
  },
  Carboplatin = {
    "drug_name":"Carboplatin",
    "pathway":"generic cytotoxic",
    "tumor_in_vitro":4,
    "tumor_in_vivo":6,
    "phase_one_safety_data":6,
    "cns_data_with_response":10,
    "brain_penetration":0,
    "fda_approval":10,
    "total_points":36,
  },
  Irinotecan = {
    "drug_name":"Irinotecan",
    "pathway":"generic cytotoxic",
    "tumor_in_vitro":4,
    "tumor_in_vivo":6,
    "phase_one_safety_data":6,
    "cns_data_with_response":10,
    "brain_penetration":0,
    "fda_approval":10,
    "total_points":36,
  },
  CCNU = {
    "drug_name":"CCNU",
    "pathway":"generic cytotoxic",
    "tumor_in_vitro":4,
    "tumor_in_vivo":3,
    "phase_one_safety_data":6,
    "cns_data_with_response":10,
    "brain_penetration":0,
    "fda_approval":10,
    "total_points":33,
  },
  Temozolomide = {
    "drug_name":"Temozolomide",
    "pathway":"generic cytotoxic",
    "tumor_in_vitro":4,
    "tumor_in_vivo":6,
    "phase_one_safety_data":6,
    "cns_data_with_response":10,
    "brain_penetration":0,
    "fda_approval":10,
    "total_points":36,
  },
  Ponatinib = {
    "drug_name":"Ponatinib",
    "pathway":"RET",
    "tumor_in_vitro":4,
    "tumor_in_vivo":6,
    "phase_one_safety_data":0,
    "cns_data_with_response":5,
    "brain_penetration":10,
    "fda_approval":10,
    "total_points":35,
  },
  Cabozantinib = {
    "drug_name":"Cabozantinib",
    "pathway":"RET",
    "tumor_in_vitro":4,
    "tumor_in_vivo":6,
    "phase_one_safety_data":6,
    "cns_data_with_response":10,
    "brain_penetration":10,
    "fda_approval":10,
    "total_points":46,
  },
  Alectinib = {
    "drug_name":"Alectinib",
    "pathway":"RET",
    "tumor_in_vitro":2,
    "tumor_in_vivo":0,
    "phase_one_safety_data":0,
    "cns_data_with_response":5,
    "brain_penetration":10,
    "fda_approval":10,
    "total_points":27,
  },
  Loxo_292 = {
    "drug_name":"Loxo_292",
    "pathway":"RET",
    "tumor_in_vitro":2,
    "tumor_in_vivo":6,
    "phase_one_safety_data":3,
    "cns_data_with_response":5,
    "brain_penetration":10,
    "fda_approval":0,
    "total_points":26,
  },
  BLU_667 = {
    "drug_name":"BLU_667",
    "pathway":"RET",
    "tumor_in_vitro":2,
    "tumor_in_vivo":3,
    "phase_one_safety_data":0,
    "cns_data_with_response":5,
    "brain_penetration":0,
    "fda_approval":0,
    "total_points":10,
  }];

  var RESPONSE;

  if (PW === "") {
    RESPONSE = IDT;
  } else {
    RESPONSE = IDT.filter(function(object) {
      return object.pathway === PW ;
    })
  }
  return JSON.stringify(RESPONSE);
  // return table of information
}
