openapi: 3.0.2
info:
  version: '0.1'
  title: 'CNS_TAP Intrinsic Drug Table'
  description: CNS_TAP Intrinsic Drug Table
servers:
  - url: /99999/intrinsicDrugTable
    description: CNS_TAP Intrinsic Drug Table
paths:
  /intrinsicDrugTable:
    post:
      description: CNS_TAP Intrinsic Drug Table
      operationId: CNS_TAP Intrinsic Drug Table
      requestBody:
        description: inputs
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/input'
      responses:
        '200':
          description: response
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/output'
        default:
          description: unexpected error
          content:
            application/json:
              schema:
                $ref: 'https://demo.kgrid.org/schemas/basicerror.yaml'
components:
  schemas:
    input:
      required:
        - pathway
      properties:
        pathway:
          type: string
          example: AKT
    output:
      required:
        - result
      properties:
        result:
          type: object
