openapi: 3.0.2
info:
  version: '2.0'
  title: 'CNS_TAP Intrinsic Drug Table'
  description: Intrinsic Drug Table values for CNS-TAP
  license:
     name: GNU General Public License v3 (GPL-3)
     url: >-
       https://tldrlegal.com/license/gnu-general-public-license-v3-(gpl-3)#fulltext
  contact:
    name: KGrid Team
    email: kgrid-developers@umich.edu
    url: 'http://kgrid.org'
servers:
  - url: /CNSTAPIDT/intrinsicDrugTable/2.0
    description: Intrinsic Drug Table values for CNS-TAP
tags:
  - name: KO Endpoints
    description: CNSTAPIDT Endpoints
paths:
  /intrinsicDrugTable:
    post:
      tags:
        - KO Endpoints
      description: Intrinsic Drug Table values for CNS-TAP
      operationId: CNSTAPIDT
      requestBody:
        description: inputs
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/input'
      responses:
        '200':
          description: response
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/output'
        default:
          description: unexpected error
          content:
            application/json:
              schema:
                $ref: 'https://demo.kgrid.org/schemas/basicerror.yaml'
components:
  schemas:
    input:
      required:
        - pathway
      properties:
        pathway:
          type: string
          example: AKT
    output:
      required:
        - result
      properties:
        result:
          type: object
          additionalProperties:
            type: object
