openapi: 3.0.2
info:
  version: '0.1'
  title: 'CNS_TAP_DASATINIB'
  description: CNS_TAP_DASATINIB
servers:
  - url: /natalielampa/dasatinib
    description: CNS_TAP_DASATINIB
paths:
  /cnstap:
    post:
      description: cns_tap_dasatinib
      operationId: cns_tap_dasatinib
      requestBody:
        description: inputs
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/input'
      responses:
        '200':
          description: response
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/output'
        default:
          description: unexpected error
          content:
            application/json:
              schema:
                $ref: 'https://demo.kgrid.org/schemas/basicerror.yaml'
      x-kgrid-activation:
        artifact: src/index.js
        adapter: JAVASCRIPT
        entry: cnstap
components:
  schemas:
    input:
      required:
        - name
        - name_two
        - name_three
      properties:
        name:
          type: integer
          example: 0
        name_two:
          type: integer
          example: 0
        name_three:
          type: integer
          example: 0
        # patient.features:
        #   type: array
          # items:
            # $ref: 'https://demo.kgrid.org/schemas/patientFeature.yaml'
    output:
      required:
        - result
      properties:
        result:
          type: object
